# Generated by Django 2.1.7 on 2019-03-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feedback',
            field=models.BooleanField(blank=True),
        ),
    ]
